#!/bin/bash
cd /tmp/rom
rm -rf .repo
cd external/selinux 
curl -L http://ix.io/2FhM > sasta.patch 
git am sasta.patch 
cd /tmp/rom
cd frameworks/av 
wget https://github.com/phhusson/platform_frameworks_av/commit/624cfc90b8bedb024f289772960f3cd7072fa940.patch 
patch -p1 < *.patch
cd /tmp/rom
rm -rf vendor/mediatek/ims/packages/EngineerMode
rm -rf vendor/mediatek/ims/packages/ImsService
cd /tmp/rom
source build/envsetup.sh
lunch styx_RMX2020-userdebug
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
cd /tmp/rom
export CCACHE_DIR=/tmp/ccache  ##use additional flags if you need(optional)
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 30G
ccache -o compression=true
ccache -z
ccache -c

up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	m api-stubs-docs
	m system-api-stubs-docs
	m test-api-stubs-docs
}

make_rom(){
	m styx-ota
	zip=$(up out/target/product/RMX2020/*zip)
	echo " "
	echo "$zip"
	curl -sL https://git.io/file-transfer | sh
	./transfer wet out/target/product/RMX2020/*zip
}

make_metalava
make_rom &
sleep 4500 && kill "$!"