#!/bin/bash

url=https://ghostmirror.hitesh920.workers.dev/losloslos.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf losloslos.tar.gz
echo "unzip done"
find losloslos.tar.gz -delete
