#!/bin/bash

url=https://ghostmirror.hitesh920.workers.dev/enforcinglos.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf enforcinglos.tar.gz
echo "unzip done"
find enforcinglos.tar.gz -delete
